# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: README.md
          key: some-key
  job2:
    runs-on: ubuntu-latest
    container: ubuntu:22.04
    steps:
      - uses: actions/cache/restore@v3
        with:
          path: README.md
          key: some-key
      - run: echo test
