# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: README.md
          key: some-key
  job2:
    if: "!contains(github.event.head_commit.message, '#skip_checks') && !contains(github.event.pull_request.title, '#skip_checks')"
    runs-on: ubuntu-latest
    container: ubuntu:22.04
    env:
      SECRET_VAR: ${{ secrets.NAME_SECRET }}
    needs: job1
    steps:
      - run: echo $SECRET_VAR
    #steps:
    #  - run: apt-get update && apt-get install -y zstd
    #  - uses: actions/cache/restore@v3
    #    with:
    #      path: README.md
    #      key: some-key
    #  - run: echo test
    #  - name: Dump GitHub context
    #    env:
    #      GITHUB_CONTEXT: ${{ toJson(github) }}
    #    run: |
    #      echo "$GITHUB_CONTEXT"
